### ISSUE TITLE
sigma_similarity and sigma don't works properly

### ISSUE THREAD

**Issue by frack113** [SigmaHQ/sigma#1866]
Hi,
sigma_similarity don't work properly.

- [x] Sigmac start instead of of sigma_similarity #1875
- [x] decode return error #1875
- [x] TypeError: object of type 'NodeSubexpression' has no len() 
- [x] NotImplementedError: Base backend doesn't support multiple conditions

works
```
D:\FrackSigma\Sigma\tools>python sigma_similarity -r -m 90 ..\rules\windows\sysmon
100% (91 of 91) |################################################| Elapsed Time: 0:00:00 Time:  0:00:00
````

don't works
```
python sigma_similarity -r -m 90 ..\rules\windows\builtin
Traceback (most recent call last):
  File "D:\FrackSigma\Sigma\tools\sigma_similarity", line 5, in <module>
    main()
  File "D:\FrackSigma\Sigma\tools\sigma\sigma_similarity.py", line 75, in main
    converted = {
  File "D:\FrackSigma\Sigma\tools\sigma\sigma_similarity.py", line 76, in <dictcomp>
    str(path): list(sigma_collection.generate(backend))
  File "D:\FrackSigma\Sigma\tools\sigma\parser\collection.py", line 80, in generate
    [ backend.generate(parser) for parser in self.parsers ]
  File "D:\FrackSigma\Sigma\tools\sigma\parser\collection.py", line 80, in <listcomp>
    [ backend.generate(parser) for parser in self.parsers ]
  File "D:\FrackSigma\Sigma\tools\sigma\backends\base.py", line 120, in generate
    query = self.generateQuery(parsed)
  File "D:\FrackSigma\Sigma\tools\sigma\backends\base.py", line 135, in generateQuery
    result = self.generateNode(parsed.parsedSearch)
  File "D:\FrackSigma\Sigma\tools\sigma\backends\base.py", line 171, in generateNode
    return self.applyOverrides(self.generateSubexpressionNode(node))
  File "D:\FrackSigma\Sigma\tools\sigma\backends\base.py", line 279, in generateSubexpressionNode
    generated = self.generateNode(node.items)
  File "D:\FrackSigma\Sigma\tools\sigma\backends\base.py", line 161, in generateNode
    return self.applyOverrides(self.generateANDNode(node))
  File "D:\FrackSigma\Sigma\tools\sigma\backends\base.py", line 252, in generateANDNode
    generated = [ self.generateNode(val) for val in node ]
  File "D:\FrackSigma\Sigma\tools\sigma\backends\base.py", line 252, in <listcomp>
    generated = [ self.generateNode(val) for val in node ]
  File "D:\FrackSigma\Sigma\tools\sigma\backends\base.py", line 165, in generateNode
    return self.applyOverrides(self.generateNOTNode(node))
  File "D:\FrackSigma\Sigma\tools\sigma\backends\base.py", line 272, in generateNOTNode
    generated = self.generateNode(node.item)
  File "D:\FrackSigma\Sigma\tools\sigma\backends\base.py", line 171, in generateNode
    return self.applyOverrides(self.generateSubexpressionNode(node))
  File "D:\FrackSigma\Sigma\tools\sigma\backends\base.py", line 280, in generateSubexpressionNode
    if len(node.items) == 1:
TypeError: object of type 'NodeSubexpression' has no len()
```

**Comment by frack113** [comment]
https://github.com/SigmaHQ/sigma/blob/0103b148f7957818236ec1257f29d367c307eee7/tools/sigma/backends/base.py#L280 was include in 7ba375dea07cea8d3135282bc2837563c91420d6
There are many errors in the tests in action logs
I try this, works but don't know the on-board effects
```python
        try: 
            if len(node.items) == 1:
                # A sub expression with length 1 is not a proper sub expression, no self.subExpression required
                return generated
        except:
            pass # TypeError: object of type 'NodeSubexpression' has no len()
```
