### ISSUE TITLE
Starting with Sigma

### ISSUE THREAD

**Issue by john-snow168** [SigmaHQ/sigma#3875]
Hi Team,
I just started with Sigma and got the following error. (also is there any communication channel [Slac etc])
Command: python3 sigmac  

Error
```
Traceback (most recent call last):
  File "sigmac", line 5, in <module>
    main()
  File "sigma/tools/sigma/sigmac.py", line 187, in main
    argparser = set_argparser()
  File "sigma/tools/sigma/sigmac.py", line 120, in set_argparser
    argparser.add_argument("--target", "-t", choices=backends.getBackendDict().keys(), help="Output target format")
  File "sigma/tools/sigma/backends/discovery.py", line 31, in getBackendDict
    return getClassDict(getBackendList())
  File "sigma/tools/sigma/backends/discovery.py", line 28, in getBackendList
    return getAllSubclasses(path, "backends", BaseBackend)
  File "sigma/tools/sigma/tools.py", line 24, in getAllSubclasses
    module = importlib.import_module(".{}.{}".format(import_base, name), __package__)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "sigma/tools/sigma/backends/lacework.py", line 500, in <module>
    class LaceworkQuery:
  File "sigma/tools/sigma/backends/lacework.py", line 661, in LaceworkQuery
    def get_query_sources(logsource_name, logsource_config) -> list[str]:
TypeError: 'type' object is not subscriptable
```

**Comment by nasbench** [comment]
Hi and thanks for opening this issue.

Unfortunately, the issue you encountered is currently known while using sigmac from the tool directory by cloning the project and it won't be fixed until the next release.

I suggest you use a stable version of sigmac available via pip [here](https://pypi.org/project/sigmatools/). You could install it using the following command  `pip install sigmatools`

From there you should be able to use `sigmac` directly from the command-line without issues.

If you still want to use sigmac via cloning this repo. I suggest to you this "hotfix" by commenting the following section from the file [lacework.py](https://github.com/SigmaHQ/sigma/blob/39d4b577a1277a8c027f565704cda208373a3d70/tools/sigma/backends/lacework.py#L660-L672)

```python
    #@staticmethod
    #def get_query_sources(logsource_name, logsource_config) -> list[str]:
    #    # 4. validate service has a source mapping
    #    source = safe_get(logsource_config, 'source', str)
    #    sources = safe_get(logsource_config, 'sources', list)
#
    #    if sources:
    #        return sources
    #    elif source:
    #        return [source]
#
    #    raise BackendError(
    #        f'Lacework backend could not determine source for logsource {logsource_name}')
```

Please note that `sigmac` is approaching its EOL and fixes and patches are "best effort". I highly suggest you take a look at [**PySIGMA**](https://github.com/SigmaHQ/pySigma) as it's the currently supported and future of the SIGMA project.

**Comment by nasbench** [comment]
The issue has been fixed in https://github.com/SigmaHQ/sigma/issues/3875

Closing this as complete.

**Comment by nasbench** [comment]
There are a couple of slack channels out there from SOC Prime and others. But not "officialy" related to SIGMA HQ.

If you have questions you can always send me a DM in twitter https://twitter.com/nas_bench

**Comment by john-snow168** [comment]
Got you. Thanks
